server:
  port: 8000

msa:
  client:
    user-url: http://localhost:8081
    order-url: http://localhost:8082
    product-url: http://localhost:8083

token:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  cloud:
    kubernetes:
      config:
        enabled: false
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: api-gateway